#autocomplete
[[plugins]]
repo='Shougo/deoplete.nvim'
on_i = 1
hook_add='''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 0
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#enable_camel_case = 0
let g:deoplete#enable_ignore_case = 0
let g:deoplete#enable_refresh_always = 0
let g:deoplete#enable_smart_case = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#max_list = 10000
inoremap <expr><CR>  pumvisible() ? deoplcache#close_popup() : "<CR>"
'''

#deoplete python
[[plugins]]
repo ='deoplete-plugins/deoplete-jedi'
on_ft = 'python'
on_i = 1
hook_add='''
let g:deoplete#sources#jedi#server_timeout=100
let g:deoplete#sources#jedi#statement_length=100
let g:jedi#completions_enabled = 0
'''

#python補完
[[plugins]]
repo ='davidhalter/jedi-vim'
on_ft = 'python'
on_i = 1
hook_add='''
let g:jedi#force_py_version = 3
let g:jedi#auto_initialization = 1
let g:jedi#popup_select_first = 0 
let g:jedi#popup_on_dot = 0
autocmd FileType python setlocal completeopt-=preview
'''

#c/c++補完
[[plugins]]
repo='zchee/deoplete-clang'
on_ft = ['c', 'cpp']
on_i = 1
depends = ['deoplete.nvim']
hook_add='''
let g:deoplete#sources#clang#libclang_path='/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
let g:deoplete#sources#clang#clang_header='/Library/Developer/CommandLineTools/usr/lib/clang'
autocmd FileType c,cpp setlocal completeopt-=preview
'''

#c/c++ header補完
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
on_i = 1
depends = ['deoplete.nvim']

# ディレクトリ表示プラグイン
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add='''
nnoremap <silent><C-t> :NERDTreeToggle<CR>
'''

# UI
[[plugins]]
repo = 'Shougo/unite.vim'

# vim上でプログラム実行
[[plugins]]
repo='thinca/vim-quickrun'
hook_add='''
autocmd FileType c,cpp,python map <buffer>  <F7> :QuickRun<CR>
'''

# 括弧補完
[[plugins]]
on_i = 1
repo='cohama/lexima.vim'

# tagbar
[[plugins]]
repo='majutsushi/tagbar'
hook_add='''
nmap <F8> :TagbarToggle<CR>
'''
