# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

# ファイル操作
[[plugins]]
repo = 'Shougo/defx.nvim'

# require defx-icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# defx costum
[[plugins]]
repo = 'kristijanhusak/defx-icons'

# defx costum
[[plugins]]
repo = 'kristijanhusak/defx-git'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# git
[[plugins]]
repo='airblade/vim-gitgutter'

# color theme
[[plugins]]
repo="altercation/vim-colors-solarized"

# color theme
[[plugins]]
repo="lifepillar/vim-solarized8"

# powerline
[[plugins]]
repo='vim-airline/vim-airline'

# powerline theme
[[plugins]]
repo='vim-airline/vim-airline-themes'

# vim window size
[[plugins]]
repo='simeji/winresizer'

# language pack
[[plugins]]
repo="sheerun/vim-polyglot"

# 括弧補完
[[plugins]]
on_i = 1
repo='jiangmiao/auto-pairs'

# コメントアウト
[[plugins]]
repo='scrooloose/nerdcommenter'

# インデント可視化
[[plugins]]
repo='Yggdroot/indentLine'

# スタート画面
[[plugins]]
repo='mhinz/vim-startify'
