# ディレクトリ表示プラグイン
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add='''
nnoremap <silent><C-t> :NERDTreeToggle<CR>
'''

# UI
[[plugins]]
repo = 'Shougo/unite.vim'

# 括弧補完
[[plugins]]
on_i = 1
repo='cohama/lexima.vim'

# tagbar
[[plugins]]
repo='majutsushi/tagbar'
hook_add='''
nmap <F8> :TagbarToggle<CR>
'''
