# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

# ファイル操作
[[plugins]]
repo = 'Shougo/defx.nvim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# git
[[plugins]]
repo='airblade/vim-gitgutter'

# color theme
[[plugins]]
repo="altercation/vim-colors-solarized"

# powerline
[[plugins]]
repo='vim-airline/vim-airline'

# powerline theme
[[plugins]]
repo='vim-airline/vim-airline-themes'

# vim window size
[[plugins]]
repo='simeji/winresizer'

# language pack
[[plugins]]
repo="sheerun/vim-polyglot"

# 括弧補完
[[plugins]]
on_i = 1
repo='cohama/lexima.vim'

# コメントアウト
[[plugins]]
repo='scrooloose/nerdcommenter'

# インデント可視化
[[plugins]]
repo='Yggdroot/indentLine'