#autocomplete
[[plugins]]
repo='Shougo/deoplete.nvim'
on_i = 1
hook_add='''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 0
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#enable_camel_case = 0
let g:deoplete#enable_ignore_case = 0
let g:deoplete#enable_refresh_always = 0
let g:deoplete#enable_smart_case = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#max_list = 10000
inoremap <expr><CR>  pumvisible() ? deoplcache#close_popup() : "<CR>"
autocmd FileType python,c,cpp setlocal completeopt-=preview
'''

# ディレクトリ表示プラグイン
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add='''
nnoremap <silent><C-t> :NERDTreeToggle<CR>
'''

# UI
[[plugins]]
repo = 'Shougo/unite.vim'

# 括弧補完
[[plugins]]
on_i = 1
repo='cohama/lexima.vim'

# tagbar
[[plugins]]
repo='majutsushi/tagbar'
hook_add='''
nmap <F8> :TagbarToggle<CR>
'''
