#syntaxチェッカー
[[plugins]]
repo='w0rp/ale'
hook_add='''
let g:ale_linters = {
		\ 'python': ['flake8', 'pyflakes', 'autopep8'],
		\ 'c' : ['gcc'],
		\ 'cpp' : ['gcc'],
		\ }
let g:ale_fixers = {
	    \'python':['autopep8'],
	    \'c':['clang-format'],
	    \'cpp':['clang-format'],
	    \}
let g:ale_sign_column_always = 1
let g:ale_use_global_executables = 1
let g:ale_lint_on_text_changed = 1
nmap <S-f> <Plug>(ale_fix)"
let g:ale_python_flake8_args = '--max-line-length=150'
let g:ale_python_autopep8_args = '--max-line-length=150'
'''

#git
[[plugins]]
repo = 'tpope/vim-fugitive'

#git
[[plugins]]
repo='airblade/vim-gitgutter'

#powerline
[[plugins]]
repo='vim-airline/vim-airline'
hook_add='''
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'unique_tail'
'''

#powerline theme
[[plugins]]
repo='vim-airline/vim-airline-themes'
hook_add='''
let g:airline_theme='one'
'''

#テンプレート
[[plugins]]
repo='mattn/sonictemplate-vim'
hook_add='''
let g:sonictemplate_vim_template_dir = '~/sonictemplate'
'''

#vim window size 変更
[[plugins]]
repo='simeji/winresizer'

#コメントアウトプラグイン	
[[plugins]]
repo='scrooloose/nerdcommenter'

# 括弧やクオート
[[plugins]]
repo='tpope/vim-surround'
