#python補完
[[plugins]]
repo ='davidhalter/jedi-vim'
on_ft = 'python'
hook_add='''
let g:jedi#completions_command = "<C-n>"
let g:jedi#popup_select_first = 0 
let g:jedi#popup_on_dot = 0
autocmd FileType python setlocal completeopt-=preview
'''

#pyenv用プラグイン
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
hook_add='''
if jedi#init_python()
  function! s:jedi_auto_force_py_version() abort
    let g:jedi#force_py_version = pyenv#python#get_internal_major_version()
  endfunction
  augroup vim-pyenv-custom-augroup
    autocmd! *
    autocmd User vim-pyenv-activate-post   call s:jedi_auto_force_py_version()
    autocmd User vim-pyenv-deactivate-post call s:jedi_auto_force_py_version()
  augroup END
endif
'''

#lightline色プラグイン
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
if !has('gui_running')
  set t_Co=256
endif
let g:lightline = {
    \ 'colorscheme': 'solarized',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'gitbranch', 'readonly', 'filename', 'modified' ],
    \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ],
    \ },
	\ 'component_function': {
    \   'gitbranch': 'fugitive#head'
    \ },
    \ }
'''

#シンタックスエラー数などをlightlineに表示プラグイン
[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add='''
let g:lightline.component_expand = {
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }
let g:lightline.component_type = {
      \     'linter_checking': 'left',
      \     'linter_warnings': 'warning',
      \     'linter_errors': 'error',
      \     'linter_ok': 'left',
      \ }
'''

#syntaxチェッカー
[[plugins]]
repo = 'w0rp/ale'
hook_add='''
let g:ale_linters = {
    \ 'python': ['flake8', 'pyflakes'],
    \ }
let g:ale_sign_column_always = 1
let g:ale_lint_on_text_changed = 1
let g:airline#extensions#ale#enabled = 1
'''


#テンプレート
[[plugins]]
repo='mattn/sonictemplate-vim'
hook_add='''
let g:sonictemplate_vim_template_dir = '~/sonictemplate'
'''

#vim window size 変更
[[plugins]]
repo='simeji/winresizer'

#コメントアウトプラグイン	
[[plugins]]
repo='scrooloose/nerdcommenter'

#git
[[plugins]]
repo='tpope/vim-fugitive'

